### ISSUE TITLE
`ObjectMapperCodeGenerator` doesn't recurse for `serializeObject()`

### ISSUE THREAD

**Issue by Nadyita** [EventSaucePHP/ObjectHydrator#75]
I have a (shortened) class like this:

```php
class ImplantConfig {
	/** psalm-param int<1,300> $ql */
	public function __construct(
		public int $ql=300,
		public ?SlotConfig $head=null,
	) {
	}
}
```

When I use the `ObjectMapperCodeGenerator`, it recurses into `SlotConfig` and further down, but only for hydration.
The generated code looks like this:

```php
    /**
     * @template T of object
     * @param class-string<T> $className
     * @return T
     */
    public function hydrateObject(string $className, array $payload): object
    {
        return match($className) {
            'Nadybot\Modules\IMPLANT_MODULE\ImplantConfig' => $this->hydrateNadybot⚡️Modules⚡️IMPLANT_MODULE⚡️ImplantConfig($payload),
                'Nadybot\Modules\IMPLANT_MODULE\SlotConfig' => $this->hydrateNadybot⚡️Modules⚡️IMPLANT_MODULE⚡️SlotConfig($payload),
                'Nadybot\Modules\IMPLANT_MODULE\SymbiantSlot' => $this->hydrateNadybot⚡️Modules⚡️IMPLANT_MODULE⚡️SymbiantSlot($payload),
                'Nadybot\Modules\IMPLANT_MODULE\AbilityAmount' => $this->hydrateNadybot⚡️Modules⚡️IMPLANT_MODULE⚡️AbilityAmount($payload),
            default => throw UnableToHydrateObject::noHydrationDefined($className, $this->hydrationStack),
        };
    }
```

In comparison, the serialization code is this:

```php
    /**
     * @template T
     *
     * @param T               $object
     * @param class-string<T> $className
     */
    public function serializeObjectOfType(object $object, string $className): mixed
    {
        try {
            return match($className) {
                'array' => $this->serializeValuearray($object),
            'Ramsey\Uuid\UuidInterface' => $this->serializeValueRamsey⚡️Uuid⚡️UuidInterface($object),
            'DateTime' => $this->serializeValueDateTime($object),
            'DateTimeImmutable' => $this->serializeValueDateTimeImmutable($object),
            'DateTimeInterface' => $this->serializeValueDateTimeInterface($object),
            'Nadybot\Modules\IMPLANT_MODULE\ImplantConfig' => $this->serializeObjectNadybot⚡️Modules⚡️IMPLANT_MODULE⚡️ImplantConfig($object),
                default => throw new \LogicException("No serialization defined for $className"),
            };
        } catch (\Throwable $exception) {
            throw UnableToSerializeObject::dueToError($className, $exception);
        }
    }
```
As you can see, it doesn't recurse, and to me, that is a bug. I'm using the latest `1.5.0` release. Am I mistaken?

**Comment by frankdejonge** [comment]
Hi, I'm trying to reproduce your issue, but I'm failing to do so. I did uncover another issue, which is resolved in the PR. Could you see if this represents your case? And if not, can you provide a case to reproduce your issue?

**Comment by Nadyita** [comment]
Sadly, it doesn't fix my issue. I'll try to create a minimum working example, because my current codebase is 760k LOC

**Comment by Nadyita** [comment]
Here we go:

```php
<?php

declare(strict_types=1);

require_once './vendor/autoload.php';

use EventSauce\ObjectHydrator\ObjectMapperCodeGenerator;

class A
{
    public function __construct(
        public string $x,
    ) {
    }
}

class B
{
    public function __construct(
        public ?A $a,
    ) {
    }
}

$b = new B(a: new A(x: "here"));

$mapper = new ObjectMapperCodeGenerator();
$code = $mapper->dump([$b::class], 'Seri\\Tester');
$fileName = tempnam('/tmp/', 'seri_');
file_put_contents($fileName, $code);
require_once $fileName;
$serializer = new \Seri\Tester();
echo(json_encode($serializer->serializeObject($b)) . PHP_EOL);
```

This throws the error `Call to undefined method Seri\Tester::serializeObjectA()`, because it doesn't recurse into it. hydration works perfectly fine, though.

**Comment by frankdejonge** [comment]
Right, the issue seems to be in the class expanding mechanism, If you add `A::class` into the dump function it's all fine.

**Comment by frankdejonge** [comment]
I think I've got it. Can you checkout the PR I linked earlier?

**Comment by frankdejonge** [comment]
Checking out an unintended side-effect of the fix now.

**Comment by frankdejonge** [comment]
Your code should work in the PR branch now.

**Comment by Nadyita** [comment]
Yes, but the original one doesn't, because it's generating duplications. Minimum working proof:

```php
<?php

declare(strict_types=1);

require_once './vendor/autoload.php';

use EventSauce\ObjectHydrator\ObjectMapperCodeGenerator;

class A
{
    public function __construct(
        public string $x,
    ) {
    }
}

class B
{
    public function __construct(
        public A $a,
    ) {
    }
}

class C
{
    public function __construct(
        public A $a,
        public B $b,
    ) {
    }
}

$c = new C(a: new A(x: "haha!"), b: new B(a: new A(x: "here")));

$mapper = new ObjectMapperCodeGenerator();
$code = $mapper->dump([$c::class], 'Seri\\Tester');
$fileName = tempnam('/tmp/', 'seri_');
file_put_contents($fileName, $code);
require_once $fileName;
$serializer = new \Seri\Tester();
echo(json_encode($serializer->serializeObject($b)) . PHP_EOL);
```

This throws `Cannot redeclare Seri\Tester::serializeObjectA()`

**Comment by frankdejonge** [comment]
A quick `array_unique` resolved that.

**Comment by Nadyita** [comment]
Okay, now I'm getting other errors. Might take a break for today, but it seems it happens when I have this:

```php
<?php declare(strict_types=1);

namespace Nadybot\Modules\IMPLANT_MODULE;

class SymbiantSlot {
	/**
	 * @param AbilityAmount[] $reqs
	 * @param AbilityAmount[] $mods
	 *
	 * @psalm-param list<AbilityAmount> $reqs
	 * @psalm-param list<AbilityAmount> $mods
	 */
	public function __construct(
		public string $name,
		public int $treatment,
		public int $level,
		public array $reqs,
		public array $mods,
	) {
	}
}
```

For this case, it reports `No serialization defined for Nadybot\\Modules\\IMPLANT_MODULE\\AbilityAmount`, so my guess is that annotations are ignored. I gotta go to bed, but maybe you can modify the previous example to reproduce the error. Sorry for being such a pain.

**Comment by frankdejonge** [comment]
The class expansion mechanism is trying to do its best to resolve everything, but the more things are defined in relation to custom tooling, like psalm or via docblocks, the more its guesswork and not exact science. My recommendation is always to use `league/construct-finder` (which I also built) to resolve all classes and not rely on the class expansion mechanism that's built into this.

**Comment by Nadyita** [comment]
Well, I don't have much choice with array not being typed in PHP :shrug: and I thought that the algorithm for serialization and hydration was working the same way.
Sadly, I can't use tools that scan directories, because the code allows 3rd party plugins and who knows which of them are serializing which object. That is why I wrote a wrapper that compiles hydrators and serializers on the fly, so I don't have to know where all this is. And whenever the serializer throws exceptions, it uses the reflection-based one.

**Comment by frankdejonge** [comment]
You can also take a stab at trying to solve it yourself. I'm doing my best to help you, providing support for a free tool that I literally do not benefit from in any shape or capacity.

**Comment by Nadyita** [comment]
Yes, I could, but it might take some time, before I'm familiar enough with the code to fix this kind of thing. Sadly, time doesn't grow on trees, and I was in the middle of preparing a new release when I noticed performance impacts when using the reflection version. So yes, I'm gonna try and fix it, but it will take a bit of time :disappointed:

**Comment by Nadyita** [comment]
@WyriHaximus It sounds like yes, but I think I worked around the issue in the meantime. Idon't really remember, it's been quite a while 😁
